apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: seafile-secrets
    namespace: seafile
    env: seafile.secret

resources:
  - certificate-seafile.yml
  - deploy-mariadb.yml
  - deploy-redis.yml
  - deploy-seafile.yml
  - ingressroute-seafile.yml
  - ns-seafile.yml
  - pvc-mariadb-data.yml
  - pvc-seafile.yml
  - svc-mariadb.yml
  - svc-memcached.yml
  - svc-seafile.yml
  - svc-redis.yml

images:
  - name: mariadb
    newName: mariadb
    newTag: "10.11"
  - name: seafile
    newName: seafileltd/seafile-mc
    newTag: "13.0.11"
  - name: redis
    newName: redis
    newTag: "8.2.1-alpine"
