- name: Install OMV Plugins
  ansible.builtin.apt:
    pkg:
      - openmediavault-k8s
      - openmediavault-clamav
      - openmediavault-sharerootfs

- name: Set machine hostname
  ansible.builtin.copy:
    content: "{{ inventory_hostname }}\n"
    dest: /etc/hostname
    force: yes

# HTTPS configuration
- name: SSL configuration
  block:
    - name: Copy SSL intermediary certificate
      ansible.builtin.copy:
        dest: /etc/ssl/certs/omv-intermediary.crt
        content: "{{ ssl_intermediary_cert }}"
        owner: root
        mode: "0644"

    - name: Copy SSL intermediary key
      ansible.builtin.copy:
        dest: /etc/ssl/private/omv-intermediary.key
        content: "{{ ssl_intermediary_key }}"
        owner: root
        mode: "0600"

    - name: Copy leaf certs generation script
      ansible.builtin.copy:
        src: ./files/generate-leaf-from-intermediary.sh
        dest: /usr/local/bin/generate-leaf-from-intermediary
        owner: root
        mode: "0755"

    - name: Generate leaf certificate
      ansible.builtin.command:
        argv:
          - generate-leaf-from-intermediary

    - name: Get leaf cert content
      ansible.builtin.slurp:
        src: /etc/ssl/certs/omv.crt
      register: leaf_cert_content

    - name: Copy SSL certificate full chain
      ansible.builtin.copy:
        dest: /etc/ssl/certs/omv-chain.crt
        content: "{{ leaf_cert_content.content | b64decode }}{{ ssl_intermediary_cert }}{{ ca_cert }}"
        owner: root
        mode: "0644"

    - name: Generate intermediary SSL certificate chain
      ansible.builtin.copy:
        dest: /etc/ssl/certs/omv-intermediary-chain.crt
        content: "{{ ssl_intermediary_cert }}{{ ca_cert }}"
        owner: root
        mode: "0644"

    - name: Copy update script
      ansible.builtin.copy:
        src: ./files/omv-ssl-update-certs.sh
        dest: /usr/local/bin/omv-ssl-update-certs
        owner: root
        mode: "0755"

    - name: Copy nginx SSL cert script setter
      ansible.builtin.copy:
        src: ./files/omv-set-nginx-ssl-cert.sh
        dest: /usr/local/bin/omv-set-nginx-ssl-cert
        owner: root
        mode: "0755"

    - name: Add leaf SSL cert to OMV database
      ansible.builtin.command:
        argv:
          - omv-ssl-update-certs
          - "757f842e-faf0-11e8-a284-3a6331353066"
          - "/etc/ssl/certs/omv-chain.crt"
          - "/etc/ssl/private/omv.key"

    - name: Add intermediary SSL cert to OMV database
      ansible.builtin.command:
        argv:
          - omv-ssl-update-certs
          - "657f842e-faf0-11e8-a284-3a6331353067"
          - "/etc/ssl/certs/omv-intermediary-chain.crt"
          - "/etc/ssl/private/omv-intermediary.key"

    - name: Set nginx to use leaf SSL cert
      ansible.builtin.command:
        argv:
          - omv-set-nginx-ssl-cert
          - "757f842e-faf0-11e8-a284-3a6331353066"

    - name: Generate kube CA secret manifest
      ansible.builtin.template:
        src: templates/ca-omv-cluster.yml.j2
        dest: /etc/ssl/private/ca-omv-cluster.yml
        mode: "0600"
        owner: root
        group: root
